### ISSUE TITLE
useSetAtom x only use actions with atom

### ISSUE THREAD

**Issue by Byevenes** [next-pay/next-pay#2]
https://github.com/next-pay/next-pay/blob/39891d142250985f814cda1f661ad437d9bb8151/apps/live-demo/src/components/service-selector.tsx#L17C47-L17C47

You can replace `const [, setService] = useAtom(serviceAtom);` => `const setService = useSetAtom(serviceAtom);`

**Comment by Yhozen** [comment]
closed with [6821a53](https://github.com/next-pay/next-pay/commit/6821a53d44709f2987149bbcade9f9a8f93a82d0)
